### ISSUE TITLE
Issue templates?

### ISSUE THREAD

**Issue by MOJOliciousFTW** [frdedynamics/find_the_duck#19]
Do you have a preffered template for issues? Maybe add a issue template or two to get better issue descriptions.

**Comment by swampbear** [comment]
Got no experience with using it perosanaly, but added the standard ones for bug and feature request. Any tips to what a good issue template should contain?

**Comment by MOJOliciousFTW** [comment]
I use the same standard ones.

Not much of a tip, but I like adjustments if repo uses different type of software. Good example: https://github.com/tcunit/TcUnit/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
